---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
      - id: nixpkgs-fmt
