---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: trailing-whitespace
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
      - id: nixpkgs-fmt
  - repo: https://github.com/Vimjas/vint
    rev: v0.4a4
    hooks:
      - id: vint
