---
keys:
  - &david 73C1C5DF51E7BB9285E9A2625960278CE235F821
  - &dh-framework 3727C581CD4E4DF55F66FDA9C04B64DABDB187CB
creation_rules:
  - path_regex: nixosConfigurations/dh-framework/[^/]+\.(yml|yaml)$
    key_groups:
    - pgp:
        - *dh-framework
  - path_regex: nixos/config/users/david/[^/]+\.(yml|yaml)$
    key_groups:
    - pgp:
        - *david
        - *dh-framework
