---
keys:
  - &david 73C1C5DF51E7BB9285E9A2625960278CE235F821
  - &dh-laptop2 F8F09E1A8E96E4041C32BE674B46F44EF073C77A
  - &dh-framework 3727C581CD4E4DF55F66FDA9C04B64DABDB187CB
creation_rules:
  - path_regex: nixosConfigurations/dh-laptop2/[^/]+\.yml$
    key_groups:
    - pgp:
        - *dh-laptop2
  - path_regex: nixosConfigurations/[^/]+\.yml$
    key_groups:
    - pgp:
        - *dh-framework
  - path_regex: nixos/config/users/david/[^/]+\.yml$
    key_groups:
    - pgp:
        - *david
        - *dh-laptop2
        - *dh-framework
