david-password: ENC[AES256_GCM,data:4VT3uCUnnjVy29VthL/mEwz28EveaTVtRdi2rPlMTm75IydVCasnoi5keAtkwDbGerNg3wF1ksm1v6382C8b+PFBWDFqTlI/bNfTD+PSeJEXfWBYU/GBMJWpFHhQYOY/nM8zH9D1x0fA8A==,iv:hWIx4VnaZDs/yBy+lcnNZqEHlDKLcLKhxk6mpfH7QdE=,tag:oBT1UTqa+mW/rpnwqZrdOw==,type:str]
gh-config: ENC[AES256_GCM,data:+A5W9I/03yU+32NjMpOU8FD+dJjggnbDPPZD6GWDYFKRLxEt7di6gyjpNXD8xn5SQMRt3cQDLz0M/Wek1c/0Es8NN825rDiSp531nl5fhou1nshLcW0irLHL7CX6ciL+l9RCQA8h6wKAi4mZ,iv:8KaFrJnjOsCcoepsojhnBmsCpLeYeM42XQYhj40LehQ=,tag:I9bq0sV7DmAQHAyQMgd8ng==,type:str]
work-email-pw: ENC[AES256_GCM,data:tr3FJX4lztSJ0bNXk8O4Gw==,iv:ksR4EvLiuEvlu2FwWlJaJjJ6qxsKcY4dvd+KVAO4tOA=,tag:t1PPt+MakNVRgivIzm3xSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-14T22:38:23Z"
    mac: ENC[AES256_GCM,data:4INaQgSaHt7DFHGDGR7C6sGin2EmDMxX3qZ4EOKlpToEM0KDj6MefCM4vAGo3FN7wXtX9mGacG1lp6nxMgD8O7vADXbZz893lpLANFzDegcLC3uygNZBkZvWv1CrxOduNLdMJRaLUGg+Yk12nWK8m6bAN6/4hZhStrzCvOeQM24=,iv:fnODdLpM8HhaQh48E4Y28CLPrQ2pkMq3kp6zZAhZwEY=,tag:mUMKFBnpXDDFH4faOZRSIw==,type:str]
    pgp:
        - created_at: "2022-05-14T16:16:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4Dr5Uglojnih0SAQdAGN65tDQxc83rRly1RZ/C10yarFMdtbzKpc5RkdzuvXAw
            kaCIJu3dcoE8MOflf63IqGJnPPqWCsPKFYXijTdn9sFhaZ8n5WR4A3IeOPZqPew4
            0lwBIu7fbC4YhLcfEfV4/eO9RQtPGTc77wB2Ls3lk3vBe/GuEABvag0yhfFSUWsb
            +wxrQ2bJJVvw103hWwtPDJqRGZBg+LlrfiID29bqhqrdbR3rQPFDoM8rsiGzoQ==
            =yCpV
            -----END PGP MESSAGE-----
          fp: 73C1C5DF51E7BB9285E9A2625960278CE235F821
        - created_at: "2022-05-14T16:16:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0tG9E7wc8d6AQgAlMFsB1jYCJU1O4BmLCfiL1PnUYC93Vc96O7Qu0lffDhJ
            3jIa2PVbytQGijlHpDsj7T9o48xiqzXyP7RpuJukUxA63YZ/zqhq5QZTo7fDJJlA
            8XUj31o3gBFhpkObal8SYyvBLd5zzSegdouAGJEeQt/rIXh5D2JAqZj280z5m0cF
            kdGEJ0lvhYEBmkCKlYXO54UxM/HprgzydPV8IQiw6KCAlxUeShBHqXxiuCFK9yor
            rF9QzX1Z2NNXwHeNPMI9T3ROROdAR0OX02S+KpXqWLbo+uPWpX3L6djDZii+Ua9f
            XgnWW6ZAphfVzVqZ8cJhKA3pjQFlRL3O/gYdl/abc9JcATR17FbYyii5GT9n/7KL
            FBrBgDOYLmMH7EV2LowGrQVFTI7VJltH0nvcN7ElrX/PKCymmKNOuYPH8zLsaiK3
            ADspKQmb6IkEJIJJG/8z+XNA0IrXj2qJ2fqGmN8=
            =HYzF
            -----END PGP MESSAGE-----
          fp: F8F09E1A8E96E4041C32BE674B46F44EF073C77A
        - created_at: "2022-05-14T16:16:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAwbvDq9qvPxEAQf/VjlnJ+zpnX/RDRan5yrit/wIBAFjwjthomrkY26z5Dms
            tHX61G1sNjXY+6T+SeQcndYwoBBDXguEclnqy2FHC96gZkidiFY8iPEoyKxcLvnd
            AN/UvCTPjGHCJ2DQKJ16f0ZbFnbX5qlovvnv9HH6MUhNkjSfn0doIxB/dC301Qib
            fgd4sR992ywSy58GaQn6asTmaGKez1sgdwl7KOBGUBUhP4nVGTS4Vw1f3OBX4MpI
            1rnPNnB7Jv9F/qwx2rXRuh1amxiIsWGX5B30kk4sIPDmm6n4Ullh+4B0msEkcO/E
            PH6h3pCV3B0EpBG0N14/+slZO8prKMPKikP9UxnxgtRmAQkCEEOu2RupPAgECFMF
            ZfSNcncjnIPkgYvuIVhpM2SmA/QG8GjqwV3KyDizJpHPP1zVSZ1rrl0Q8tVkzY4Q
            MhPQhzuEuZd/HitvzKvBcaPjL3uRagLwv2kOcKcgc2qk1zyaqVZT
            =PToq
            -----END PGP MESSAGE-----
          fp: F27C2B85BCB81A31C437E6E206EF0EAF6ABCFC44
    unencrypted_suffix: _unencrypted
    version: 3.7.1
