david-password: ENC[AES256_GCM,data:HX9zepSCQqSGPfUcvhkPa+YWJN1DUSI2DrIz6nAjwyjqE37Q8wWVwprbBf8YxZIer1t/HhABKPViVV/rXhAIf7/V+lJpz+/x/w==,iv:liegXv6sHGEHLnrt6Xtn+HCaOT3l2vvX2lx29t4AKAM=,tag:B3EBJZRappGPVxMauvC7hg==,type:str]
gh-config: ENC[AES256_GCM,data:+A5W9I/03yU+32NjMpOU8FD+dJjggnbDPPZD6GWDYFKRLxEt7di6gyjpNXD8xn5SQMRt3cQDLz0M/Wek1c/0Es8NN825rDiSp531nl5fhou1nshLcW0irLHL7CX6ciL+l9RCQA8h6wKAi4mZ,iv:8KaFrJnjOsCcoepsojhnBmsCpLeYeM42XQYhj40LehQ=,tag:I9bq0sV7DmAQHAyQMgd8ng==,type:str]
work-email-pw: ENC[AES256_GCM,data:tr3FJX4lztSJ0bNXk8O4Gw==,iv:ksR4EvLiuEvlu2FwWlJaJjJ6qxsKcY4dvd+KVAO4tOA=,tag:t1PPt+MakNVRgivIzm3xSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-18T21:01:23Z"
    mac: ENC[AES256_GCM,data:9NiZR0OHxbrEp52rbktYi27l1TnHTofF4OnDRpM3N3OVXDUOb9B4MkJS32IRvwIR5Xo6SMC0W0YqX6U/xsft8Llx6YmOyuw9lgtZXsszW42BT+UnD60AH2qayTpNprAIdOchsrJP0hPRuXD8GadhScayRDJkiervvXrT+HCBXOY=,iv:jNbmBJdvT2vXnsEQYGNSIFV3tgM1/ERPlO1+xDO/Vww=,tag:rnjBNSh9iUVHgdhwBfWW3w==,type:str]
    pgp:
        - created_at: "2022-07-18T20:52:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4Dr5Uglojnih0SAQdA4sb7xS3EIRzqVgAxh1SYsgjhQWdjaqLw96OTpXHujAsw
            XPqRW+jzk7KNTrc14gued+eiL47nvJ3ViTI1va9SkpOxKfkbYqLEBXYu0rzPIiV7
            0lwBdhWS5YG8b/3GcYRl3631gf8YwPwOfDXSm68TbTuxMTqlNK5nEF4HYUmUw/qN
            HJV2HaK+hKx9foAO4PkUdOdFJA2wVhgYCOufK3NHaBpjUC73XrZIp+sDFEnoIg==
            =QCEc
            -----END PGP MESSAGE-----
          fp: 73C1C5DF51E7BB9285E9A2625960278CE235F821
        - created_at: "2022-07-18T20:52:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0tG9E7wc8d6AQf/bkkPRweQHdL5iveZXnUBnAhP0dq6WNxd3EMR0PGsEAyV
            ZHWLk60RMTdI6gyfiJhv96DRXRRKGbe3UNe6gPZMS12FS/tPF35lTzMF9s/p6nQD
            sDAcz2J4WZc8RvABRLI9ZmKns7uY/t/RwNRbfO0gydisFeMR+HM4406v8Ziw68Dn
            sZbH50o5g1Fu0HxINY1Ziq1mtbQuW8OxVeXJKsfd3/WUsO6nc6wO7xopBh4JzMro
            fgsEEJokr/gB3R6J34Bm9s7MezIF5n+AMzaOQxLH1Oj1MEZ/pdmGb/XCMktIeVo0
            W//U1DEUymDk+nmTiUm4N9QGxldnTMedSUnp0ybBtNJcATgxW/d91by5VIFu0fUn
            xnOrQx9RcTa8ZqbkrSE9FfUgr3kkFWhgQWaUqegzvHMWH5Zt2sug1LFyMhMmAHWV
            eki5KkuyO+2r4gp3VMqKYnRk2Z6gjpCMxzwLrMs=
            =omyS
            -----END PGP MESSAGE-----
          fp: F8F09E1A8E96E4041C32BE674B46F44EF073C77A
        - created_at: "2022-07-18T20:52:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8BLZNq9sYfLAQf/bRhUK+SqI3gh/rhCV1NOnqN9RIoxTwzsT3VWYjVOrcxW
            IjgSDDZ+3Ny9usC6K6flicgT4ABM4+4KoBIVZrFs7/PjOmG8cypqi1QL1AxgoQFk
            nZojeGHRCX8/t9PLAcNMr02PNkeld9/PoA4i31VlC3nt7CeGMqrWl81ECFQmmDjO
            GJfoqCkiOVln3CRJC91IVlpgfWmvXGxacuBeb6eYKsh3KqK9hN0gM3EAkrWzEbe+
            o1RIsaheSt17102WIwNBPydmW3N+3mzyAS52nCtod4T4hQsCf1w1CU+sJ1T8kmlM
            7wLjfWLPEuIUyFflyeU65J28ABgVgCqw9vK1ejjYtdRmAQkCEJ0rh3/E/mMNWU2g
            wNnq/rXjGDdIDs0jMVP+wlI1k8ksL6eo+b8kxkZEBE9Qv0D++tNQyLJRAHNmhLAq
            eRPzvMWXmkbIkfJGVmdF0lHPyUT5dqakGxbWgZbXjHu0d/6x8XLQ
            =h3U3
            -----END PGP MESSAGE-----
          fp: 3727C581CD4E4DF55F66FDA9C04B64DABDB187CB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
