david-password: ENC[AES256_GCM,data:4VT3uCUnnjVy29VthL/mEwz28EveaTVtRdi2rPlMTm75IydVCasnoi5keAtkwDbGerNg3wF1ksm1v6382C8b+PFBWDFqTlI/bNfTD+PSeJEXfWBYU/GBMJWpFHhQYOY/nM8zH9D1x0fA8A==,iv:hWIx4VnaZDs/yBy+lcnNZqEHlDKLcLKhxk6mpfH7QdE=,tag:oBT1UTqa+mW/rpnwqZrdOw==,type:str]
gh-config: ENC[AES256_GCM,data:+A5W9I/03yU+32NjMpOU8FD+dJjggnbDPPZD6GWDYFKRLxEt7di6gyjpNXD8xn5SQMRt3cQDLz0M/Wek1c/0Es8NN825rDiSp531nl5fhou1nshLcW0irLHL7CX6ciL+l9RCQA8h6wKAi4mZ,iv:8KaFrJnjOsCcoepsojhnBmsCpLeYeM42XQYhj40LehQ=,tag:I9bq0sV7DmAQHAyQMgd8ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-27T11:01:16Z"
    mac: ENC[AES256_GCM,data:4wPicpqUd+3emjMRtl1N2xFt3iLAP4JLN2wjO7v/N6F0/Pc/w6qF5rsDNfM+9lmHNSp2FFmGPtbI3gIvQGoD9Z7MGpGhRpLXRkjNAXE6/0Y+FkSEZiKYMEjDBub5d+K5BPbbJzvwbpdk3EL1KLP/BNC5fYr1yRi+dWnmXvSz7RQ=,iv:LgoOwievsyZ3GuPefO+lctiIHKz9C6hwajiXq+ewDtM=,tag:FYKfej/6tlGk9xWa7rvWuQ==,type:str]
    pgp:
        - created_at: "2021-12-22T09:18:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hE4Dr5Uglojnih0SAQdAg6y1W4mGoEMbPjGswqnWgBgptvDQZLCJNhVO8LBr7wgg
            elRUcQgZyibS+SLT307vEVwyImG32uugm7O0hfjv3vrSVgE8sPaPsJ57WzXPt36s
            BVxBA4SWRXyITihPXdp1zcvgY2RnlN6tDL1omRPPoFJrWns7czy/gdQQnVZsQj3K
            Gp0m3Wfh/Q3uCWz+ZcV3i0jVQYL8EjYt
            =Zs4q
            -----END PGP MESSAGE-----
          fp: 73C1C5DF51E7BB9285E9A2625960278CE235F821
        - created_at: "2021-12-22T09:18:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0tG9E7wc8d6AQf6AvSMnlxW2QuQK0hrdFh7zlLMkCIC1raav38Q+C6PD2sy
            GEOQDYAQHQ5hplbVUiBSqJQr0WGT0wBZfE+eZAorSwUekFTyYLU3S0LE5eQxUuan
            VuBH83uglhKhMYptP9AjCoSYNPOqzxp2i563WemLdK6dBgmhKGVNlPJjFJYrsl3H
            MlS9oPVNXbK45k6qLAUS4zd+NwPloxNkxBgLadP7y1ZdtqVyefQJ7fOPJTJPRdpm
            RDCli1opGyOq1py6PiPED/BlgP4GlDdr2GlExbXsZmQREdmoAVURG6+jOmbhHSp6
            kTwuDIV9CpQgzkQWpFEBBndEA7rbTbOQDZYGEZtoRdJWAY4XIr/tKBY7w++FwYhH
            70v3jK3w+TbdwTwoOv1Kixt2TwafL/kta0FShIsKNuYGC5QCggl2vU8V/XO/e99M
            skOGQx4KwISGCe7iArDQILnOuOhy8K4=
            =czmU
            -----END PGP MESSAGE-----
          fp: F8F09E1A8E96E4041C32BE674B46F44EF073C77A
    unencrypted_suffix: _unencrypted
    version: 3.7.1
