# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
      ];

      kernelModules = [
        "vfat"
        "nls_cp437"
        "nls_iso8859-1"
        "usbhid"
        "kvm-intel"
        "dm-snapshot"
        "i915"
      ];

      luks = {
        # Support for Yubikey PBA
        yubikeySupport = true;

        devices."nixos-enc" = {
          device = "/dev/disk/by-partlabel/root";

          yubikey = {
            slot = 2;
            twoFactor = true;
            gracePeriod = 30;
            keyLength = 64;
            saltLength = 16;

            storage = {
              device = "/dev/disk/by-label/boot";
              fsType = "vfat";
              path = "/crypt-storage/default";
            };
          };
        };
      };
    };

    extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/fsroot";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

    "/home" = {
      device = "/dev/disk/by-label/fsroot";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-label/fsroot";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  };

  swapDevices = [{
    device = "/dev/disk/by-label/swap";
    priority = 2048;
  }];

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;
  hardware.cpu.intel.sgx.provision.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
}
