[
  ./sys/cloud.nix
  ./sys/core.nix
  ./sys/dev.nix
  ./sys/fonts.nix
  ./sys/git.nix
  ./sys/gnupg.nix
  ./sys/keyboard.nix
  ./sys/music.nix
  ./sys/sec.nix
  ./sys/shell.nix
  ./sys/ssh.nix
  ./programs/neofetch.nix
]
