[
  ./programs/neofetch.nix
  ./sys/cloud.nix
  ./sys/core.nix
  ./sys/desktop
  ./sys/desktop/chat/discord.nix
  ./sys/desktop/chat/matrix.nix
  ./sys/desktop/chat/msteams.nix
  ./sys/desktop/sway.nix
  ./sys/desktop/web
  ./sys/dev.nix
  ./sys/fonts.nix
  ./sys/git.nix
  ./sys/gnupg.nix
  ./sys/helix.nix
  ./sys/keyboard.nix
  ./sys/music.nix
  ./sys/podman.nix
  ./sys/sec.nix
  ./sys/shell.nix
  ./sys/ssh.nix
  ./sys/video.nix
  ./sys/virt.nix
]
