[
  ./sys/backup.nix
  ./sys/clamav.nix
  ./sys/core.nix
  ./sys/desktop/gnome.nix
  ./sys/desktop/sway.nix
  ./sys/hardware.nix
  ./sys/libvirtd.nix
  ./sys/print.nix
  ./sys/podman.nix
  ./sys/sshd.nix
  ./sys/virtualbox.nix
]
