name: Checks
on:
  push:
jobs:
  check-eval:
    name: Install Nix
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: nix -vL --show-trace flake check --no-build

